import { Router } from "express";
import blogsRouter from "./blogs.js";
import leadsRouter from "./leads.js";
import clientsRouter from "./clients.js";
import projectsRouter from "./projects.js";
import invoicesRouter from "./invoices.js";
import paymentsRouter from "./payments.js";
import teamRouter from "./team.js";
import analyticsRouter from "./analytics.js";
import chatsRouter from "./chats.js";
import demoRequestsRouter from "./demo-requests.js";
import aiCallsRouter from "./ai-calls.js";
import tasksRouter from "./tasks.js";
import proposalsRouter from "./proposals.js";
import expensesRouter from "./expenses.js";
import payrollRouter from "./payroll.js";
import filesRouter from "./files.js";
import workflowsRouter from "./workflows.js";
import integrationsRouter from "./integrations.js";
import aiToolsRouter from "./ai-tools.js";
import companyRouter from "./company.js";
import contentRouter from "./content.js";
import operationsRouter from "./operations.js";
import searchRouter from "./search.js";
import { requireCurvvtechAdmin } from "../../../middleware/requireCurvvtechAdmin.js";
import { enforceAdminPermissions } from "../../../middleware/enforceAdminPermissions.js";

const router = Router();

router.use(requireCurvvtechAdmin);
router.use(enforceAdminPermissions);

router.use("/blogs", blogsRouter);
router.use("/leads", leadsRouter);
router.use("/clients", clientsRouter);
router.use("/projects", projectsRouter);
router.use("/invoices", invoicesRouter);
router.use("/payments", paymentsRouter);
router.use("/team", teamRouter);
router.use("/analytics", analyticsRouter);
router.use("/chats", chatsRouter);
router.use("/demo-requests", demoRequestsRouter);
router.use("/ai-calls", aiCallsRouter);
router.use("/tasks", tasksRouter);
router.use("/proposals", proposalsRouter);
router.use("/expenses", expensesRouter);
router.use("/payroll", payrollRouter);
router.use("/files", filesRouter);
router.use("/workflows", workflowsRouter);
router.use("/integrations", integrationsRouter);
router.use("/ai", aiToolsRouter);
router.use("/company", companyRouter);
router.use("/content", contentRouter);
router.use("/operations", operationsRouter);
router.use("/search", searchRouter);

export default router;
